export function ProjectNotes() {
  return <>
    <section id="foundation" className="principles-section" aria-labelledby="principles-title">
      <div className="principles-intro"><p className="eyebrow">Built with care</p><h2 id="principles-title">Better planning begins<br />with better information.</h2><p>A small, sourced collection makes a useful starting point. Facts, uncertainty, and opinion each have their own place.</p></div>
      <div className="principle-list"><article><span>01</span><div><h3>Follow the evidence</h3><p>Property details show sources, confidence, and verification dates. Conflicts require review; unknown details stay unknown.</p></div></article><article><span>02</span><div><h3>Discover a setting</h3><p>Filter by geography, brand, property type, and recorded experiences. Setting tags describe context, rather than a quality score.</p></div></article><article><span>03</span><div><h3>Plan in stages</h3><p>Compare sourced property details now. Assess cash and points with your own quotes. Trip planning is an upcoming stage. Each is reviewed before the next begins.</p></div></article></div>
    </section>
    <section id="roadmap" className="roadmap-section" aria-labelledby="roadmap-title"><div className="section-heading"><div><p className="eyebrow">A clear path forward</p><h2 id="roadmap-title">Taking shape, one stage at a time.</h2></div><span className="quiet-label">Current and planned capabilities</span></div>
      <div className="roadmap-grid">{[{ stage: 3, title: 'Compare your contenders', description: 'See two to four properties together, with unavailable details made explicit.' }, { stage: 4, title: 'Make your points count', description: 'Assess cash and points with rates you enter and visible assumptions.' }, { stage: 6, title: 'Bring your trip together', description: 'Connect hotel stays and see the cash and points your trip needs.' }].map((module, index) => <article className="roadmap-card" key={module.stage}><div className="card-top"><span className="card-number">0{index + 1}</span><span className="card-stage">Stage {module.stage}</span></div><h3>{module.title}</h3><p>{module.description}</p><span className="planned-label">{module.stage <= 4 ? 'Available' : 'Planned'}</span></article>)}</div><p className="roadmap-note">Next milestone: Recommendation Engine. Each stage is reviewed before the next begins.</p>
    </section>
  </>;
}
