import { useEffect, useState } from 'react';
import type { Catalog } from '../types/catalog';
import type { ExplorerQuery } from '../lib/catalog/explorer';
import { calculatorHref, explorerHref, propertyHref } from '../lib/navigation/routes';
import { countryName, humanize } from '../lib/catalog/presentation';
import { experienceTagSchema } from '../lib/validation/catalog';
import { FIT_LABELS, FIT_METHODOLOGY } from '../lib/scoring/methodology';
import type { FitKey } from '../lib/scoring/methodology';
import { initialRecommendationInput, recommendProperties } from '../lib/scoring/recommendations';
import type { RecommendationInput, RecommendationResult } from '../lib/scoring/recommendations';
import { formatMoney, formatPoints } from '../lib/points/calculator';
import { POINTS_POLICY } from '../lib/points/policy';
import { EvidenceValue } from './EvidenceValue';
import { RecommendationQuote } from './RecommendationQuote';

const rounded = (value: number | null) => value === null ? 'Unknown' : value.toFixed(1);

function Candidate({ result, catalog, request, query, comparisonSlugs }: { result: RecommendationResult; catalog: Catalog; request: RecommendationInput; query: ExplorerQuery; comparisonSlugs: string[] }) {
  const property = catalog.properties.find((p) => p.id === result.propertyId)!;
  const e = result.economics;
  return <article className="recommendation-card" aria-label={`Recommendation for ${property.name}`} data-property-id={property.id}>
    <header className="recommendation-card-header"><div><p className="eyebrow">{humanize(result.eligibility)} candidate</p><h3><a href={propertyHref(property.slug, query, comparisonSlugs)}>{property.name}</a></h3></div><div className="fit-summary"><strong>{result.fit.score === null ? 'Partial trip fit' : `${rounded(result.fit.score)}/100 trip fit`}</strong><span>{rounded(result.fit.coverage)}% of active weight assessed</span><span>Possible fit: {rounded(result.fit.lowerBound)}–{rounded(result.fit.upperBound)} / 100</span></div></header>
    <p className="recommendation-summary">{result.explanation.summary}</p>
    <div className="recommendation-layers"><section aria-label="Eligibility"><h4>01 · Eligibility</h4><ul>{result.checks.map((check) => <li key={check.label}><strong>{check.label} · {humanize(check.state)}</strong><p>{check.detail}</p></li>)}</ul><p>Availability for your travel dates is not checked.</p><details className="evidence-details"><summary>Inspect eligibility evidence</summary><h4>Operating status</h4><EvidenceValue catalog={catalog} property={property} subject="operatingStatus" asOf={request.asOf} />{request.country && <><h4>Country</h4><EvidenceValue catalog={catalog} property={property} subject="country" asOf={request.asOf} /></>}{request.requiredTag && <><h4>Recorded experiences</h4><EvidenceValue catalog={catalog} property={property} subject="experienceTags" asOf={request.asOf} /></>}</details>{request.maxCashUsd !== null && <p>Budget: {formatMoney(result.budget.limitUsd, 'USD')}; cash path {formatMoney(result.budget.cashCostUsd, 'USD')}; award cash {formatMoney(result.budget.awardCashUsd, 'USD')}. Permitted method: {result.budget.bookingMethod}. Award points affordability: {result.budget.awardPointsAffordable === null ? 'Unknown' : result.budget.awardPointsAffordable ? 'Within balance' : 'Insufficient balance'}.</p>}</section>
      <section aria-label="Booking economics"><h4>03 · Booking economics</h4><strong>{e?.band ?? 'Booking value unavailable'}</strong><p>{result.explanation.bookingAction}</p><dl className="calculator-breakdown"><div><dt>Comparable cash total</dt><dd>{formatMoney(e?.cashTotal ?? null, e?.input.currency ?? 'USD')}</dd></div><div><dt>Points spent</dt><dd>{formatPoints(e?.pointsSpent ?? null)}</dd></div><div><dt>Cash payable on award</dt><dd>{formatMoney(e?.awardCash ?? null, e?.input.currency ?? 'USD')}</dd></div><div><dt>Redemption value</dt><dd>{e?.cpp == null ? 'Unknown' : `${e.cpp.toFixed(3)}¢ / point`}</dd></div><div><dt>Points shortfall</dt><dd>{formatPoints(e?.pointsShortfall ?? null)}</dd></div><div><dt>Points remaining</dt><dd>{formatPoints(e?.remainingBalance ?? null)}</dd></div></dl>
        {e && <details className="calculator-formula"><summary>Inspect booking arithmetic and quote</summary><p>Quote check-in: {result.quoteContext?.checkIn ?? 'Unknown'} · Observed: {result.quoteContext?.observedAt ?? 'Unknown'} · {e.input.nights} nights.</p><p>Net cash avoided: {formatMoney(e.netCashAvoided, e.input.currency)} = {formatMoney(e.cashTotal, e.input.currency)} − {formatMoney(e.awardCash, e.input.currency)}.</p><p>CPP = net cash avoided × manual USD conversion × 100 ÷ points spent. Conversion: {e.fx ?? 'Unknown'}; points: {e.pointsSpent ?? 'Unknown'}. {e.cpp == null ? 'CPP is unavailable until required values are known and points spent is positive.' : `Result: ${e.cpp.toFixed(3)} USD cents.`}</p><p>Personal value: {e.input.valuationCpp ?? 'Unknown'}¢. Thresholds relative to personal value: strongly cash below {e.input.thresholds.stronglyCash}; cash below {e.input.thresholds.cash}; neutral below {e.input.thresholds.good}; good below {e.input.thresholds.excellent}; excellent at or above {e.input.thresholds.excellent}.</p><p>Final quoted points used exactly; no additional fifth-night deduction. Policy: {POINTS_POLICY.version}. <a href="https://www.marriott.com/loyalty/terms/default.mi" target="_blank" rel="noopener noreferrer">Marriott terms ↗</a></p></details>}
        <a className="source-link" href={calculatorHref(query, comparisonSlugs, property.slug)}>Open full points calculator ↗</a></section></div>
    <details className="fit-details"><summary>02 · Inspect trip-fit components</summary><p>{FIT_METHODOLOGY.uncertainty} Active weight: {result.fit.activeWeight}; known weight: {result.fit.knownWeight}. Bounds = (supported contributions ÷ active weight) × 100 through ((supported contributions + unknown weight) ÷ active weight) × 100. Full score is unknown until all active weight is assessed.</p>
      <div className="fit-components">{result.fit.components.map((component) => <section key={component.key}><h4>{component.label} · {component.weight}% weight</h4><p><strong>{!component.active ? 'Inactive' : component.score === null ? 'Unknown' : `${rounded(component.score)}/100 · contribution ${rounded(component.contribution)}`}</strong> · {humanize(component.kind)}</p><p>{component.detail}</p>{component.active && component.subject && <EvidenceValue catalog={catalog} property={property} subject={component.subject} asOf={request.asOf} />}</section>)}</div></details>
    <details className="explanation-details"><summary>04 · Why this candidate / what needs review</summary>{[['Preference strengths', result.explanation.strengths], ['Preference weaknesses', result.explanation.weaknesses], ['Missing trip-fit information', result.explanation.missing], ['Editorial strengths', result.explanation.editorialStrengths], ['Editorial weaknesses', result.explanation.editorialWeaknesses], ['Uncertainty and assumptions', result.explanation.uncertainties]].map(([label, items]) => <section key={label as string}><h4>{label}</h4>{(items as string[]).length ? <ul>{(items as string[]).map((item, i) => <li key={i}>{item}</li>)}</ul> : <p>None recorded; this is not proof of no weaknesses.</p>}</section>)}</details>
  </article>;
}

export function Recommendations({ catalog, asOf, query, comparisonSlugs }: { catalog: Catalog; asOf: string; query: ExplorerQuery; comparisonSlugs: string[] }) {
  const [input, setInput] = useState(() => initialRecommendationInput(asOf));
  const [result, setResult] = useState<ReturnType<typeof recommendProperties> | null>(null);
  const [quoteId, setQuoteId] = useState(catalog.properties[0]?.id ?? '');
  const [showExcluded, setShowExcluded] = useState(false);
  const [resetKey, setResetKey] = useState(0);
  useEffect(() => { if (result) document.getElementById('recommendation-result-title')?.focus(); }, [result]);
  const change = <K extends keyof RecommendationInput>(key: K, value: RecommendationInput[K]) => { setInput((v) => ({ ...v, [key]: value })); setResult(null); };
  const quoteProperty = catalog.properties.find((p) => p.id === quoteId);
  const number = (value: string) => value.trim() ? Number(value) : null;
  const ready = result?.success ? result : null;
  const candidates = ready?.results.filter((r) => r.eligibility !== 'excluded') ?? [];
  const excluded = ready?.results.filter((r) => r.eligibility === 'excluded') ?? [];
  return <>
    <a className="back-link" href={explorerHref(query, comparisonSlugs)}>← Back to your collection</a>
    <section className="calculator-hero"><p className="eyebrow">Your preferences · Sourced context · Visible uncertainty</p><h1 id="page-title" tabIndex={-1}>Find a fit. Understand the value.</h1><p>Start with required constraints and preferred experiences. Inspect trip fit alongside a separate booking assessment using optional quotes you enter. Entries clear on reload.</p></section>
    <form className="calculator-form recommendation-request" noValidate aria-label="Recommendation preferences" onSubmit={(event) => { event.preventDefault(); setResult(recommendProperties(catalog, input)); }}>
      <fieldset><legend>01 · Required constraints</legend><div className="calculator-fields">
        <label className="calculator-field">Required country<select aria-label="Required country" value={input.country ?? ''} onChange={(e) => change('country', e.target.value || null)}><option value="">Any country</option>{[...new Set(catalog.properties.map((p) => p.country))].sort().map((code) => <option key={code} value={code}>{countryName(code)}</option>)}</select></label>
        <label className="calculator-field">Required recorded experience<select aria-label="Required recorded experience" value={input.requiredTag ?? ''} onChange={(e) => change('requiredTag', e.target.value as RecommendationInput['requiredTag'] || null)}><option value="">No required tag</option>{experienceTagSchema.options.map((tag) => <option key={tag} value={tag}>{humanize(tag)}</option>)}</select><span>Require a recorded setting tag; this does not establish an exhaustive activity inventory.</span></label>
        <label className="calculator-field">Stay length (nights)<input aria-label="Stay length (nights)" type="number" min="1" max="60" step="1" value={Number.isNaN(input.nights) ? '' : input.nights} onChange={(e) => { setInput((v) => ({ ...v, nights: e.target.value ? Number(e.target.value) : NaN, quotes: [] })); setResult(null); }} /><span>Changing nights removes applied quotes so stay totals cannot be reused.</span></label>
        <label className="calculator-field">Requested check-in (optional)<input aria-label="Requested check-in (optional)" type="date" value={input.checkIn ?? ''} onChange={(e) => change('checkIn', e.target.value || null)} /></label>
        <label className="calculator-field">Maximum cash outlay (USD, stay total)<input aria-label="Maximum cash outlay (USD, stay total)" type="number" min="0" step="any" value={input.maxCashUsd ?? ''} onChange={(e) => change('maxCashUsd', number(e.target.value))} /><span>For an award, this limits cash still payable; points affordability is checked separately.</span></label>
        <label className="calculator-field">Permitted booking method<select aria-label="Permitted booking method" value={input.bookingMethod} onChange={(e) => change('bookingMethod', e.target.value as RecommendationInput['bookingMethod'])}><option value="either">Cash or points</option><option value="cash">Cash only</option><option value="points">Points only</option></select></label>
      </div><label className="recommendation-checkbox"><input type="checkbox" checked={input.requireLounge} onChange={(e) => change('requireLounge', e.target.checked)} />Require lounge access</label><p className="calculator-help">Lounge access remains unknown until evidence-backed benefit rules exist. A required unknown creates a provisional candidate.</p></fieldset>
      <fieldset><legend>02 · Trip-fit preferences</legend><div className="calculator-fields"><label className="calculator-field">Preferred destination<select aria-label="Preferred destination" value={input.destinationId ?? ''} onChange={(e) => change('destinationId', e.target.value || null)}><option value="">No destination preference</option>{catalog.destinations.map((d) => <option key={d.id} value={d.id}>{d.name}</option>)}</select><span>A preference affects fit; required geography belongs above.</span></label><label className="calculator-field">Preferred airport-distance scale (km)<input aria-label="Preferred airport-distance scale (km)" type="number" min="1" step="any" value={input.maxAirportKm ?? ''} onChange={(e) => change('maxAirportKm', number(e.target.value))} /><span>Shorter sourced distances score higher; driving time is not inferred.</span></label></div><div className="recommendation-tags" role="group" aria-label="Preferred experiences">{experienceTagSchema.options.map((tag) => <label key={tag}><input type="checkbox" checked={input.preferredTags.includes(tag)} onChange={(e) => change('preferredTags', e.target.checked ? [...input.preferredTags, tag].sort() : input.preferredTags.filter((t) => t !== tag))} />{humanize(tag)}</label>)}</div></fieldset>
      <details className="recommendation-methodology"><summary>Scoring methodology and configurable weights</summary><p>Method: {FIT_METHODOLOGY.version}. {FIT_METHODOLOGY.ranking} {FIT_METHODOLOGY.uncertainty}</p><p>Weights must total 100. Preferences without a target and zero-weight components are inactive. Missing active values retain their weight and uncertainty. No brand-based luxury or benefit assumptions. Custom weights are labeled trip-fit-1-custom and retained in the inspected request.</p><div className="calculator-fields">{(Object.keys(FIT_LABELS) as FitKey[]).map((key) => <label className="calculator-field" key={key}>{FIT_LABELS[key]} weight (%)<input aria-label={`${FIT_LABELS[key]} weight (%)`} type="number" min="0" max="100" step="any" value={Number.isNaN(input.weights[key]) ? '' : input.weights[key]} onChange={(e) => change('weights', { ...input.weights, [key]: e.target.value ? Number(e.target.value) : NaN })} /></label>)}</div></details>
      <div className="calculator-actions"><button className="primary-link" type="submit">Generate recommendations</button><button type="button" className="text-button" onClick={() => { setInput(initialRecommendationInput(asOf)); setResult(null); setQuoteId(catalog.properties[0]?.id ?? ''); setShowExcluded(false); setResetKey((v) => v + 1); }}>Clear recommendation inputs</button></div>
    </form>
    <details className="recommendation-quotes"><summary>03 · Optional manual booking quotes ({input.quotes.length} applied)</summary><p>No prices or fees come from the catalog. Quotes affect booking economics and required budgets; they do not add to trip-fit scores. Use final quoted totals here or the full calculator for varying nightly awards.</p><label className="calculator-field">Property for manual quote<select aria-label="Property for manual quote" value={quoteId} onChange={(e) => setQuoteId(e.target.value)}>{catalog.properties.map((p) => <option key={p.id} value={p.id}>{p.name}</option>)}</select></label>
      {quoteProperty && <RecommendationQuote key={`${quoteId}:${input.nights}:${resetKey}`} property={quoteProperty} nights={input.nights} appliedQuote={input.quotes.find((q) => q.propertyId === quoteId)} onApply={(quote) => { setInput((v) => ({ ...v, quotes: [...v.quotes.filter((q) => q.propertyId !== quote.propertyId), quote] })); setResult(null); }} onRemove={() => { setInput((v) => ({ ...v, quotes: v.quotes.filter((q) => q.propertyId !== quoteProperty.id) })); setResult(null); }} />}
    </details>
    <section className="recommendation-results" aria-labelledby="recommendation-result-title"><h2 id="recommendation-result-title" tabIndex={-1}>Your recommendations</h2>
      {!result ? <p>Generate recommendations to see candidates, constraints, score components and booking value. Changing applied inputs clears previous results.</p> : !result.success ? <div role="alert"><p>Review these inputs:</p><ul>{result.errors.map((error, i) => <li key={i}>{error}</li>)}</ul></div> : <>
        <p role="status">{candidates.length} candidates · {excluded.length} excluded · {ready!.methodologyVersion}</p><p>{FIT_METHODOLOGY.ranking} Evidence assessed as of {ready!.input.asOf}. A partial score range is not a hotel-quality rating.</p>
        <details className="recommendation-audit"><summary>Inspect request and structured results (JSON)</summary><pre>{JSON.stringify(ready, null, 2)}</pre></details>
        {!candidates.length && <p className="comparison-empty">No candidate meets the known required constraints. Review exclusions or relax a requirement.</p>}
        {candidates.map((r) => <Candidate key={r.propertyId} result={r} catalog={catalog} request={ready!.input} query={query} comparisonSlugs={comparisonSlugs} />)}
        {!!excluded.length && <><button className="text-button" onClick={() => setShowExcluded((v) => !v)} aria-expanded={showExcluded}>{showExcluded ? 'Hide' : 'Show'} excluded properties ({excluded.length})</button>{showExcluded && excluded.map((r) => <Candidate key={r.propertyId} result={r} catalog={catalog} request={ready!.input} query={query} comparisonSlugs={comparisonSlugs} />)}</>}
      </>}
    </section>
  </>;
}
