import type { Dispatch, SetStateAction } from 'react';
import type { Catalog } from '../types/catalog';
import type { ExplorerQuery } from '../lib/catalog/explorer';
import { propertyHref } from '../lib/navigation/routes';
import { calculateTrip, checkout, createStay, createTrip, EMPTY_PRICING } from '../lib/trips/trips';
import type { Trip, TripStay } from '../lib/trips/trips';
import { CURRENCIES, formatMoney, formatPoints } from '../lib/points/calculator';
import { POINTS_POLICY } from '../lib/points/policy';
import { EvidenceValue } from './EvidenceValue';

export type TripWorkspace = { trips: Trip[]; activeId: string | null; sequence: number };
const number = (value: string) => value.trim() === '' ? null : Number(value);
const shown = (value: number | null) => value === null || !Number.isFinite(value) ? '' : value;

export function TripBuilder({ catalog, asOf, query, comparisonSlugs, workspace, setWorkspace }: { catalog: Catalog; asOf: string; query: ExplorerQuery; comparisonSlugs: string[]; workspace: TripWorkspace; setWorkspace: Dispatch<SetStateAction<TripWorkspace>> }) {
  const trip = workspace.trips.find((entry) => entry.id === workspace.activeId);
  const updateTrip = (change: (current: Trip) => Trip) => setWorkspace((current) => ({ ...current, trips: current.trips.map((entry) => entry.id === trip?.id ? change(entry) : entry) }));
  const addTrip = () => setWorkspace((current) => { const id = `trip-${current.sequence}`; return { trips: [...current.trips, createTrip(id)], activeId: id, sequence: current.sequence + 1 }; });
  const addStay = () => setWorkspace((current) => ({ ...current, sequence: current.sequence + 1, trips: current.trips.map((entry) => entry.id === trip?.id ? { ...entry, stays: [...entry.stays, createStay(`stay-${current.sequence}`, catalog.properties[0]!.id)] } : entry) }));
  const result = trip ? calculateTrip(trip, catalog, asOf) : null;
  const editStay = (id: string, change: (stay: TripStay) => TripStay) => updateTrip((current) => ({ ...current, stays: current.stays.map((stay) => stay.id === id ? change(stay) : stay) }));
  const move = (index: number, delta: number) => updateTrip((current) => { const stays = [...current.stays]; [stays[index], stays[index + delta]] = [stays[index + delta]!, stays[index]!]; return { ...current, stays }; });
  const summaryRow = (label: string, value: string) => <div key={label}><dt>{label}</dt><dd>{value}</dd></div>;
  return <>
    <section className="calculator-hero"><p className="eyebrow">One journey · Every stay accounted for</p><h1 id="page-title" tabIndex={-1}>Bring your trip together.</h1><p>Connect hotel stays, choose cash or points, and inspect what your trip needs. Blank prices stay unknown; enter zero only for a confirmed zero charge.</p><p className="calculator-context">Trips and notes stay in this open page as you explore. Reloading clears them. All prices and reservation statuses are your manual entries; availability is not checked.</p></section>
    <div className="trip-toolbar"><button className="primary-link" onClick={addTrip} disabled={workspace.trips.length >= 10}>Create trip</button>{!!workspace.trips.length && <label className="calculator-field">Choose trip<select value={workspace.activeId ?? ''} onChange={(e) => setWorkspace((current) => ({ ...current, activeId: e.target.value }))}>{workspace.trips.map((entry) => <option key={entry.id} value={entry.id}>{entry.name || 'Unnamed trip'}</option>)}</select></label>}<span>Up to 10 trips · 30 stays per trip</span></div>
    {!trip ? <section className="comparison-empty"><h2>Your next journey starts here.</h2><p>Create a trip, then add hotels from the curated collection.</p></section> : <div className="trip-layout">
      <div className="calculator-form trip-editor" aria-label="Trip editor">
        <fieldset><legend>01 · Your trip</legend><div className="calculator-fields">
          <label className="calculator-field">Trip name<input value={trip.name} maxLength={200} onChange={(e) => updateTrip((current) => ({ ...current, name: e.target.value }))} /></label>
          <label className="calculator-field">Destination / region<input value={trip.destination} maxLength={2000} onChange={(e) => updateTrip((current) => ({ ...current, destination: e.target.value }))} /></label>
          <label className="calculator-field">Travel window<input value={trip.travelWindow} maxLength={2000} placeholder="Exact or approximate dates" onChange={(e) => updateTrip((current) => ({ ...current, travelWindow: e.target.value }))} /></label>
          <label className="calculator-field">Travelers<input type="number" min="1" max="100" step="1" value={shown(trip.travelers)} onChange={(e) => updateTrip((current) => ({ ...current, travelers: number(e.target.value) }))} /></label>
          <label className="calculator-field">Trip points balance<input aria-label="Trip points balance" type="number" min="0" step="1" value={shown(trip.balance)} onChange={(e) => updateTrip((current) => ({ ...current, balance: number(e.target.value) }))} /><span>Checked against the entire trip; other trips do not reserve points.</span></label>
          <label className="calculator-field">Trip value (USD cents per point)<input aria-label="Trip value (USD cents per point)" type="number" min="0" step="any" value={shown(trip.valuationCpp)} onChange={(e) => updateTrip((current) => ({ ...current, valuationCpp: number(e.target.value) }))} /><span>0.8¢ is an editable planning assumption.</span></label>
          <label className="calculator-field trip-wide">Trip notes / planned activities<textarea value={trip.notes} maxLength={2000} onChange={(e) => updateTrip((current) => ({ ...current, notes: e.target.value }))} /></label>
        </div></fieldset>
        <div className="trip-section-heading"><h2>02 · Your hotel stays</h2><a href="#trip-summary" onClick={(e) => { e.preventDefault(); document.getElementById('trip-summary')?.scrollIntoView(); document.getElementById('trip-summary')?.focus({ preventScroll: true }); }}>View trip totals ↓</a></div>
        {!trip.stays.length && <p className="calculator-help">Add your first hotel. Each stay is calculated separately, including any confirmed award discount.</p>}
        {trip.stays.map((stay, index) => {
          const property = catalog.properties.find((entry) => entry.id === stay.propertyId);
          const entry = result?.success ? result.stays[index] : null;
          const p = stay.pricing;
          const pricing = <K extends keyof TripStay['pricing']>(key: K, value: TripStay['pricing'][K]) => editStay(stay.id, (current) => ({ ...current, pricing: { ...current.pricing, [key]: value } }));
          const priceField = (key: 'cashRoom' | 'cashTaxes' | 'cashFees' | 'awardCash' | 'awardPoints' | 'usdPerCurrency', label: string, integer = false) => <label className="calculator-field">{label}<input type="number" min="0" step={integer ? '1' : 'any'} value={shown(p[key])} onChange={(e) => pricing(key, number(e.target.value))} /></label>;
          const dateValid = Number.isInteger(p.nights) && p.nights >= 1 && p.nights <= 60;
          return <article className="trip-stay" aria-label={`Stay ${index + 1}`} key={stay.id}>
            <div className="trip-section-heading"><h3>Stay {index + 1}</h3><div className="trip-actions"><button className="text-button" disabled={index === 0} onClick={() => move(index, -1)} aria-label={`Move stay ${index + 1} earlier`}>↑ Earlier</button><button className="text-button" disabled={index === trip.stays.length - 1} onClick={() => move(index, 1)} aria-label={`Move stay ${index + 1} later`}>↓ Later</button><button className="text-button" onClick={() => updateTrip((current) => ({ ...current, stays: current.stays.filter((item) => item.id !== stay.id) }))}>Remove stay {index + 1}</button></div></div>
            <div className="calculator-fields">
              <label className="calculator-field trip-wide">Hotel<select aria-label="Hotel" value={stay.propertyId} onChange={(e) => editStay(stay.id, (current) => ({ ...createStay(current.id, e.target.value), notes: current.notes, pricing: { ...EMPTY_PRICING, nights: current.pricing.nights, nightlyPoints: [] } }))}>{catalog.properties.map((record) => <option key={record.id} value={record.id}>{record.name}</option>)}</select><span>Changing hotel clears dates, reservation status and quote inputs.</span></label>
              <label className="calculator-field">Check-in date<input aria-label="Check-in date" type="date" value={stay.checkIn ?? ''} onChange={(e) => editStay(stay.id, (current) => ({ ...current, checkIn: e.target.value || null, observedAt: null, pricing: { ...EMPTY_PRICING, nights: p.nights, currency: p.currency, nightlyPoints: [] } }))} /><span>Changing date clears the quote. Check-out: {dateValid ? checkout(stay.checkIn, p.nights) ?? 'Unknown' : 'Unknown'}.</span></label>
              <label className="calculator-field">Nights<input aria-label="Nights" type="number" min="1" max="60" step="1" value={shown(p.nights)} onChange={(e) => editStay(stay.id, (current) => ({ ...current, observedAt: null, pricing: { ...current.pricing, nights: number(e.target.value) ?? NaN, cashRoom: p.cashBasis === 'total' ? null : p.cashRoom, cashTaxes: null, cashFees: null, awardCash: null, awardPoints: p.awardBasis === 'total' ? null : p.awardPoints, nightlyPoints: p.awardBasis === 'varying' && Number.isInteger(number(e.target.value)) && Number(e.target.value) >= 1 && Number(e.target.value) <= 60 ? Array<number | null>(Number(e.target.value)).fill(null) : [] } }))} /><span>1–60 nights. Editing nights clears stay-total costs, final award totals and variable nightly quotes.</span></label>
              <label className="calculator-field">Booking method<select value={stay.bookingMethod} onChange={(e) => editStay(stay.id, (current) => ({ ...current, bookingMethod: e.target.value as TripStay['bookingMethod'] }))}><option value="cash">Cash</option><option value="points">Points + cash due</option></select></label>
              <label className="calculator-field">Reservation status (your entry)<select value={stay.reservationStatus} onChange={(e) => editStay(stay.id, (current) => ({ ...current, reservationStatus: e.target.value as TripStay['reservationStatus'] }))}><option value="idea">Idea</option><option value="planned">Planned</option><option value="reserved">Reserved</option></select></label>
              <label className="calculator-field trip-wide">Stay notes<textarea value={stay.notes} maxLength={2000} onChange={(e) => editStay(stay.id, (current) => ({ ...current, notes: e.target.value }))} /></label>
            </div>
            <details className="trip-pricing" open><summary>Manual pricing & quote context</summary><p className="calculator-help">Enter both options to inspect redemption value. Only the chosen booking method contributes to trip spending. Taxes, fees and award cash below are totals for this stay.</p><div className="calculator-fields">
              <label className="calculator-field">Stay currency<select aria-label="Stay currency" value={p.currency} onChange={(e) => editStay(stay.id, (current) => ({ ...current, observedAt: null, pricing: { ...EMPTY_PRICING, nights: p.nights, currency: e.target.value as typeof p.currency, nightlyPoints: [] } }))}>{CURRENCIES.map((currency) => <option key={currency}>{currency}</option>)}</select><span>Changing currency clears all quote amounts and FX.</span></label>
              <label className="calculator-field">Cash room price basis<select value={p.cashBasis} onChange={(e) => editStay(stay.id, (current) => ({ ...current, pricing: { ...p, cashBasis: e.target.value as typeof p.cashBasis, cashRoom: null } }))}><option value="nightly">Nightly room rate</option><option value="total">Total room cost</option></select></label>
              {priceField('cashRoom', `${p.cashBasis === 'nightly' ? 'Nightly room rate' : 'Total room cost'} (${p.currency})`)}{priceField('cashTaxes', `Cash taxes, stay total (${p.currency})`)}{priceField('cashFees', `Cash mandatory fees, stay total (${p.currency})`)}
              <label className="calculator-field">Award points basis<select value={p.awardBasis} onChange={(e) => editStay(stay.id, (current) => ({ ...current, pricing: { ...p, awardBasis: e.target.value as typeof p.awardBasis, awardPoints: null, nightlyPoints: e.target.value === 'varying' && dateValid ? Array<number | null>(p.nights).fill(null) : [] } }))}><option value="total">Final quoted points total</option><option value="flat">Flat nightly points</option><option value="varying">Variable nightly points</option></select></label>
              {p.awardBasis !== 'varying' && priceField('awardPoints', p.awardBasis === 'total' ? 'Final quoted award points' : 'Points per night before discount', true)}
              {p.awardBasis === 'varying' && dateValid && <div className="nightly-points">{Array.from({ length: p.nights }, (_, night) => <label className="calculator-field" key={night}>Night {night + 1} points<input type="number" min="0" step="1" value={shown(p.nightlyPoints[night] ?? null)} onChange={(e) => pricing('nightlyPoints', Array.from({ length: p.nights }, (_, i) => i === night ? number(e.target.value) : p.nightlyPoints[i] ?? null))} /></label>)}</div>}
              {p.awardBasis !== 'total' && <label className="calculator-field">Stay for 5, Pay for 4 eligibility<select value={p.fifthNight} onChange={(e) => pricing('fifthNight', e.target.value as typeof p.fifthNight)}><option value="unknown">Unknown</option><option value="eligible">Eligible standard points stay</option><option value="ineligible">Ineligible</option></select></label>}
              {priceField('awardCash', `Award cash payable, stay total (${p.currency})`)}
              <label className="calculator-field">Quote products and terms<select value={p.comparable} onChange={(e) => pricing('comparable', e.target.value as typeof p.comparable)}><option value="unknown">Not confirmed</option><option value="same">Same products and terms</option><option value="different">Products or terms differ</option></select></label>
              {p.currency !== 'USD' && priceField('usdPerCurrency', `Exchange rate (USD per 1 ${p.currency})`)}
              <label className="calculator-field">Quote observed on<input type="date" value={stay.observedAt ?? ''} onChange={(e) => editStay(stay.id, (current) => ({ ...current, observedAt: e.target.value || null }))} /></label>
              <label className="calculator-field">Room / guests / inclusions<input value={stay.roomType} maxLength={2000} onChange={(e) => editStay(stay.id, (current) => ({ ...current, roomType: e.target.value }))} /></label>
              <label className="calculator-field">Cancellation terms<input value={stay.cancellation} maxLength={2000} onChange={(e) => editStay(stay.id, (current) => ({ ...current, cancellation: e.target.value }))} /></label>
            </div></details>
            {entry && <div className="trip-stay-result"><h4>Chosen booking · {stay.bookingMethod === 'cash' ? 'Cash' : 'Points + cash due'}</h4><p>{formatMoney(entry.selectedCash, p.currency)} + {formatPoints(entry.selectedPoints)}. {entry.economics.band ?? 'Booking assessment unavailable'}.</p><details><summary>Inspect stay arithmetic & assumptions</summary><dl className="calculator-breakdown">{summaryRow('Cash alternative', formatMoney(entry.economics.cashTotal, p.currency))}{summaryRow('Award cash payable', formatMoney(entry.economics.awardCash, p.currency))}{summaryRow('Award points spent', formatPoints(entry.economics.pointsSpent))}{summaryRow('Award discount savings', p.awardBasis === 'total' ? 'Already included, if applicable' : formatPoints(entry.economics.savings))}{summaryRow('Net cash avoided on award', formatMoney(entry.economics.netCashAvoided, p.currency))}{summaryRow('USD cents per point', entry.economics.cpp === null ? 'Unknown' : `${entry.economics.cpp.toFixed(3)}¢${p.comparable === 'same' ? '' : ' · illustrative'}`)}</dl><p>Cash = room cost + taxes + mandatory fees. Award cash includes all amounts still due. Discounts apply within this stay only; final quotes are used exactly as entered.</p>{!!entry.economics.freeNightIndices.length && <p>Discounted nights: {entry.economics.freeNightIndices.map((night) => night + 1).join(', ')}.</p>}<ul>{[...entry.economics.missing, ...entry.warnings].map((message, i) => <li key={i}>{message}</li>)}</ul></details></div>}
            {property && <details className="trip-evidence"><summary>Catalog facts & evidence</summary><p>Manual quotes and reservation status are user assertions. <a href={propertyHref(property.slug, query, comparisonSlugs)}>Open sourced details and separate editorial assessment ↗</a></p><h4>Operating status</h4><EvidenceValue catalog={catalog} property={property} subject="operatingStatus" asOf={asOf} /></details>}
          </article>;
        })}
        <div className="trip-actions"><button className="primary-link" disabled={trip.stays.length >= 30} onClick={addStay}>Add hotel stay</button><button className="text-button" onClick={() => setWorkspace((current) => { const trips = current.trips.filter((entry) => entry.id !== trip.id); return { ...current, trips, activeId: trips[0]?.id ?? null }; })}>Delete this trip</button></div>
      </div>
      <aside className="calculator-results trip-summary" aria-label="Trip totals" id="trip-summary" tabIndex={-1}><p className="eyebrow">Your journey, accounted for</p><h2>Trip totals</h2>{!result?.success ? <div role="alert"><h3>Check your inputs</h3><ul>{result?.errors.map((error, i) => <li key={i}>{error}</li>)}</ul><p>Totals are unavailable until invalid inputs are corrected.</p></div> : <>
        <p role="status">{result.stays.length} stays · {result.nights} nights · {result.hotelChanges} hotel {result.hotelChanges === 1 ? 'change' : 'changes'}</p>
        <dl className="calculator-breakdown">{summaryRow('Total points spent', formatPoints(result.points.total))}{result.points.missingCount > 0 && summaryRow('Known points subtotal', `${formatPoints(result.points.knownSubtotal)} · ${result.points.missingCount} incomplete stays`)}{result.cashByCurrency.map((group) => <div key={group.currency}><dt>Total cash ({group.currency})</dt><dd>{formatMoney(group.total, group.currency)}{group.missingCount > 0 && <span className="trip-subtotal">Known subtotal: {formatMoney(group.knownSubtotal, group.currency)} · {group.missingCount} incomplete stays</span>}</dd></div>)}{summaryRow('Total cash, manual USD conversion', formatMoney(result.cashUsd.total, 'USD'))}{result.cashUsd.missingCount > 0 && summaryRow('Known USD cash subtotal', `${formatMoney(result.cashUsd.knownSubtotal, 'USD')} · ${result.cashUsd.missingCount} incomplete stays`)}{summaryRow('Points remaining', formatPoints(result.remainingPoints))}{summaryRow('Points shortfall', result.shortfall === null ? 'Unknown' : `${result.points.total === null ? 'At least ' : ''}${formatPoints(result.shortfall)}`)}{summaryRow('Net cash avoided, points stays only', formatMoney(result.netCashAvoidedUsd, 'USD'))}{summaryRow('Weighted redemption value', result.redemptionCpp === null ? 'Unknown / unavailable' : `${result.redemptionCpp.toFixed(3)} USD cents/point`)}{summaryRow('Cash + personal value of points', formatMoney(result.economicCostUsd, 'USD'))}</dl>
        {!!result.stays.flatMap((entry) => entry.missing).length && <div className="calculator-notice"><h3>Incomplete chosen pricing</h3><ul>{result.stays.flatMap((entry, i) => entry.missing.map((message) => <li key={`${i}-${message}`}>Stay {i + 1}: {message}</li>))}</ul></div>}
        {!!result.warnings.length && <div className="calculator-notice"><h3>Itinerary review</h3><ul>{result.warnings.map((message, i) => <li key={i}>{message}</li>)}</ul></div>}
        <details className="calculator-formula" open><summary>How trip totals work</summary><p>Cash stays contribute their cash total and zero points. Points stays contribute their award points and all award cash due. Unknown chosen costs make the full total unknown; known subtotals are partial.</p><p>Each currency is summed separately. USD totals use only your manual exchange rates. Weighted redemption value = summed USD net cash avoided on points stays ÷ their total points × 100; all award quotes must be complete and comparable. Stay CPP values are never averaged.</p><p>Hotel changes count adjacent different properties in your chosen order. Nights count hotel nights; gaps are excluded and overlaps are flagged. A trip balance is checked once against all chosen points stays.</p></details>
        <details className="recommendation-audit"><summary>Inspect trip and structured totals (JSON)</summary><pre>{JSON.stringify(result, null, 2)}</pre></details>
      </>}<div className="calculator-policy"><h3>Calculation context</h3><p>Existing calculator policy: {POINTS_POLICY.version}, reviewed {POINTS_POLICY.verifiedAt}. <a href={POINTS_POLICY.terms} target="_blank" rel="noopener noreferrer">Marriott terms ↗</a> · <a href={POINTS_POLICY.fifthNightHelp} target="_blank" rel="noopener noreferrer">Stay for 5, Pay for 4 ↗</a></p><p>No live rates or fee waivers are assumed. Paid-stay earnings, credit-card rewards, certificates, transport and activities are excluded. Manual prices and plans are separate from catalog evidence and editorial judgments.</p></div></aside>
    </div>}
  </>;
}
